function EoM.summarize(
    results::EoM.analysis;
    plots=[],
    ss::Union{Symbol,Matrix,Vector}=:default,
    bode::Union{Symbol,Matrix,Vector}=:default,
    impulse::Union{Symbol,Matrix,Vector}=:default,
    format::Symbol=:screen,
    folder::String="output",
    filename::String=results.sys_data.name,
)
    summarize(0, [results]; plots, ss, bode, impulse, format, folder, filename)
end

# Copyright (C) 2020, Bruce Minaker

function EoM.summarize(
    vpts,
    results::Vector{EoM.analysis};
    plots=[],
    ss::Union{Symbol,Matrix,Vector}=:default,
    bode::Union{Symbol,Matrix,Vector}=:default,
    impulse::Union{Symbol,Matrix,Vector}=:default,
    vpt_name=["u" "Speed" "m/s"],
    format::Symbol=:screen,
    folder::String="output",
    filename::String=results[1].sys_data.name,
)

    if !isdefined(Main, :VSCodeServer)
        println("No VSCode detected, enforcing html format output...")
        format = :html
    end

    if format == :html
        # set up the paths
        dir_date = EoM.setup(; folder)

        # default html start and end text
        str_open = """
<!doctype html><html lang='en'><head>
<title>EoM Analysis results</title>
<meta charset='utf-8'>
<meta name='description' content='EoM Analysis result'>
<meta name='author' content='automatically generated by EoM'>
<style>
body {
    font-family: Arial, Helvetica, sans-serif;
}
h1 {
    font-family: Arial, Helvetica, sans-serif;
    font-weight: bold;
}
h2 {
    font-family: Arial, Helvetica, sans-serif;
}
table {
    border-collapse: collapse;
}
td, th {
    border: 1px solid #dddddd;
    text-align: center;
    padding: 8px;
}
tr:nth-child(even) {
    background-color: #dddddd;
}
</style>
</head>
<body>
"""

        str_close = "</body>\n</html>"

        # open the base html file to write, and start filling it
        open(joinpath(dir_date, "$filename.html"), "w") do output_f
            println(output_f, str_open)
            println(output_f, "<img src='eom_logo.png' alt='Icon' style='width:200px;'>")
            println(output_f, "<h1>Analysis results</h1>")
            println(output_f, "<p>Here are the results of the analysis of: $(results[1].sys_data.name)</p>")
        end
    else
        println("Printing summary of the analysis of: $(results[1].sys_data.name)...")
    end

    input_names = results[1].sys_data.anames
    input_units = results[1].sys_data.aunits
    output_names = results[1].sys_data.snames
    output_units = results[1].sys_data.sunits

    # get number of ins, outs, and number of vpts (velocity points)
    nin = length(input_names)
    nout = length(output_names)
    nvpts = length(vpts)

    noeigs = false

    if ss == :default
        ss = results[1].ss
    elseif typeof(ss) == Symbol
        ss = zeros(nout, nin)
    else
        error("Steady state summary request dimensions are already set!")
    end

    if bode == :default
        bode = results[1].bode
    end

    if bode == :default
        isok(x) = (x == NoDims)
        bode = isok.(dimension.(output_units * transpose(1 ./ input_units)))
    elseif typeof(bode) == Symbol
        bode = zeros(nout, nin)
    end

    if size(bode, 1) != nout || size(bode, 2) != nin
        error("Bode plot request dimensions are incompatible with system!")
    end

    if impulse == :default
        impulse = results[1].impulse
    end

    if impulse == :default
        impulse = ones(nout, nin)
    elseif typeof(impulse) == Symbol
        impulse = zeros(nout, nin)
    end

    if size(impulse, 1) != nout || size(impulse, 2) != nin
        error("Impulse response plot request dimensions are incompatible with system!")
    end

    function _plot_ss()

        labels = []
        gain = []
        # loop over outputs and inputs and vpts
        for i in 1:nout
            for j in 1:nin
                if ss[i, j] == 1
                    x = zeros(nvpts)
                    for k in 1:nvpts
                        x[k] = my_round(results[k].ss_resp[i, j])
                    end
                    push!(gain, x[1])
                    lb = "$(output_names[i])/$(input_names[j]) [$(output_units[i]/input_units[j])]"
                    push!(labels, lb)
                    # if many vpts, make plot vs velocity
                    if nvpts > 1
                        p = plot(
                            vpts,
                            x;
                            xlabel=vpt_name[2] * " [$(vpt_name[3])]",
                            ylabel=lb,
                            label="",
                        )
                        if format == :html
                            open(joinpath(dir_date, "$filename.html"), "a") do output_f
                                show(output_f, MIME("text/html"), p)
                            end
                        else
                            display(p)
                        end
                    end
                end
            end
        end

        # if only one vpt, make table of the gains
        if nvpts == 1
            column_labels = ["Output/Input", "Gain"]
            if format == :html
                str = pretty_table(String, [labels my_round.(gain)]; column_labels, backend=:html)
                open(joinpath(dir_date, "$filename.html"), "a") do output_f
                    println(output_f, "<h2>Steady state gains</h2>")
                    println(output_f, str)
                end
            else
                println("Steady state gains:")
                pretty_table([labels my_round.(gain)]; column_labels, table_format=TextTableFormat(; @text__no_vertical_lines), fit_table_in_display_vertically=false)
            end
        end
    end

    # if there are too many inputs and outputs, skip
    if nin * nout > 0 && any(ss .== 1) && sum(ss .== 1) < 16
        _plot_ss()
    end


    function _plot_eigs()

        # get eigenvalues
        l = length.(getfield.(results, :e_val))
        m = maximum(l)
        s = zeros(m, nvpts) * 1im
        for i in 1:nvpts
            s[1:l[i], i] = results[i].e_val
        end

        zs = getfield.(results, :t_zero)
        zsv = [vcat(zs[i][:]...) for i in 1:nvpts]
        lz = length.(zsv)
        mz = maximum(lz)
        sz = zeros(mz, nvpts) * 1im
        for i in 1:nvpts
            sz[1:lz[i], i] = zsv[i]
        end

        # for one velocity, chart of calcs from eigenvalues, otherwise plot eigenvalues
        if nvpts == 1
            omega = results[1].omega_n
            zeta = results[1].zeta
            tau = results[1].tau
            lambda = results[1].lambda
            column_labels = ["No.", "σ±ωi [rad/s]", "ω_n [Hz]", "ζ", "τ [s]", "λ [s]"]

            if format == :html
                str = pretty_table(String, [1:1:l[1] my_round.([s omega zeta tau lambda])]; column_labels, backend=:html)
                open(joinpath(dir_date, "$filename.html"), "a") do output_f
                    println(output_f, "<h2>Eigenvalues of minimal system</h2>")
                    println(output_f, str)
                end
            else
                println("Eigenvalues of minimal system:")
                pretty_table([1:1:l[1] my_round.([s omega zeta tau lambda])]; column_labels, table_format=TextTableFormat(; @text__no_vertical_lines), fit_table_in_display_vertically=false)
            end

            t_zero = vcat(results[1].t_zero[:]...)
            t_zero_f = vcat(results[1].t_zero_f[:]...)
            if mz > 0 && length(t_zero) < 200
                column_labels = ["No.", "σ±ωi [rad/s]", "ω [Hz]"]
                if format == :html
                    str = pretty_table(String, [1:1:lz[1] my_round.([t_zero t_zero_f])]; column_labels, backend=:html)
                    open(joinpath(dir_date, "$filename.html"), "a") do output_f
                        println(output_f, "<h2>Zeros of minimal system</h2>")
                        println(output_f, str)
                    end
                else
                    println("Zeros of minimal system:")
                    pretty_table([1:1:lz[1] my_round.([t_zero t_zero_f])]; column_labels, table_format=TextTableFormat(; @text__no_vertical_lines), fit_table_in_display_vertically=false)
                end
            end

        else

            seriestype = :scatter
            label = reshape(["$(vpt_name[1])=$i" for i in vpts], 1, nvpts)
            mc = RGB(0 / 255, 154 / 255, 250 / 255)

            sr = real.(s)
            si = imag.(s)
            vsr = vec(sr')
            vsi = vec(si')

            p = plot(vsr', vsi';
                seriestype,
                aspect_ratio=:equal,
                mc,
                label,
                xlabel="Real part [rad/s]",
                ylabel="Imaginary part [rad/s]",
                legend=false,
                marker=:o,
            )

            if format == :html
                open(joinpath(dir_date, "$filename.html"), "a") do output_f
                    println(output_f, "<h2>Locus plots</h2>")
                    show(output_f, MIME("text/html"), p)
                end
            else
                display(p)
            end

            # eliminate all zero rows
            nonzero_rows = findall(row -> any(row .!= 0), eachrow(sr))
            sr = sr[nonzero_rows, :]

            nonzero_rows = findall(row -> any(row .!= 0), eachrow(si))
            si = si[nonzero_rows, :]

            # don't plot zeros - but can't have entire row of NaN
            sr[sr.==0] .= NaN
            si[si.==0] .= NaN
            vsr = vec(sr')
            vsi = vec(si')
            if minimum(vsr) < -100
                yliml = -100
            else
                yliml = -Inf
            end

            p = plot(;
                xlabel=vpt_name[2] * " [$(vpt_name[3])]",
                ylabel="Eigenvalue [rad/s]",
                ylims=(yliml, Inf),
                widen=true,
            )

            mc = RGB(0 / 255, 154 / 255, 250 / 255)
            label = "Real"
            u = size(sr, 1)
            vv = vcat(fill(vpts, u)...)
            if length(vsr) > 0
                plot!(p, vv, vsr; seriestype, mc, label)
            end
            mc = RGB(227 / 255, 111 / 255, 71 / 255)
            label = "Imaginary"
            u = size(si, 1)
            vv = vcat(fill(vpts, u)...)
            if length(vsi) > 0
                plot!(p, vv, vsi; seriestype, mc, label)
            end

            if format == :html
                open(joinpath(dir_date, "$filename.html"), "a") do output_f
                    println(output_f, "<h2>Eigenvalue plots</h2>")
                    show(output_f, MIME("text/html"), p)
                end
            else
                display(p)
            end

            mc = RGB(0 / 255, 154 / 255, 250 / 255)
            label = ""

            function _plot(field, ylabel, section)

                vals = treat(getfield.(results, field), 1000)
                if length(vals) > 0
                    p = plot(
                        vpts,
                        vals;
                        seriestype,
                        mc,
                        label,
                        xlabel=vpt_name[2] * " [$(vpt_name[3])]",
                        ylabel,
                        ylims=(0, Inf),
                        widen=true,
                    )
                    if format == :html
                        open(joinpath(dir_date, "$filename.html"), "a") do output_f
                            println(output_f, "<h2>" * section * "</h2>")
                            show(output_f, MIME("text/html"), p)
                        end
                    else
                        display(p)
                    end
                end
            end

            _plot(:omega_n, "Natural frequency [Hz]", "Natural frequency plots")
            _plot(:zeta, "Damping ratio", "Damping ratio plots")
            _plot(:tau, "Time constant [s]", "Time constant plots")
            _plot(:lambda, "Wavelength [s]", "Wavelength plots")

            szr = real.(sz)
            szi = imag.(sz)

            # eliminate all zero rows
            nonzero_rows = findall(row -> any(row .!= 0), eachrow(szr))
            szr = szr[nonzero_rows, :]

            nonzero_rows = findall(row -> any(row .!= 0), eachrow(szi))
            szi = szi[nonzero_rows, :]

            # don't plot zeros - but can't have entire row of NaN
            szr[szr.==0] .= NaN
            szi[szi.==0] .= NaN
            vszr = vec(szr')
            vszi = vec(szi')
            if length(vszr) > 0 && minimum(filter(isfinite, vszr)) < -100
                yliml = -100
            else
                yliml = -Inf
            end
            if length(vszr) > 0 && maximum(filter(isfinite, vszr)) > 100
                ylimu = 100
            else
                ylimu = Inf
            end

            # plot zeros if they have been computed
            if length(vszr) > 0 && length(vszi) > 0
                p = plot(;
                    xlabel=vpt_name[2] * " [$(vpt_name[3])]",
                    ylabel="Zero [rad/s]",
                    ylims=(yliml, ylimu),
                    widen=true,
                )

                mc = RGB(0 / 255, 154 / 255, 250 / 255)
                label = "Real"
                u = size(szr, 1)
                vv = vcat(fill(vpts, u)...)
                if length(vszr) > 0
                    plot!(p, vv, vszr; seriestype, mc, label)
                end
                mc = RGB(227 / 255, 111 / 255, 71 / 255)
                label = "Imaginary"
                u = size(szi, 1)
                vv = vcat(fill(vpts, u)...)
                if length(vszi) > 0
                    plot!(p, vv, vszi; seriestype, mc, label)
                end

                if format == :html
                    open(joinpath(dir_date, "$filename.html"), "a") do output_f
                        println(output_f, "<h2>Zeros plot</h2>")
                        show(output_f, MIME("text/html"), p)
                    end
                else
                    display(p)
                end
            end
        end

        # print instant centre of body 1
        if nvpts == 1
            column_labels = ["No.", "Eigenvalue", "x", "y", "z", "u_x", "u_y", "u_z"]
            temp = my_round.([results[1].mode_vals (results[1].centre[1:6, 1:end])'])
            if format == :html
                link = []
                for i in axes(temp, 1)
                    push!(link, joinpath("<a href=\"$filename", "x3d", "mode_$(i)_s=$(round(results[1].mode_vals[i], digits=3)).html\">$i</a>"))
                end
                str = pretty_table(String, [link temp]; column_labels, backend=:html, allow_html_in_cells=true)
                open(joinpath(dir_date, "$filename.html"), "a") do output_f
                    println(output_f, "<h2>Rotation centres of first body for all modes, relative to G:</h2>")
                    println(output_f, str)
                end
            else
                println("Rotation centres of first body for all modes, relative to G:")
                pretty_table([1:1:size(temp, 1) temp]; column_labels, table_format=TextTableFormat(; @text__no_vertical_lines), fit_table_in_display_vertically=false)
            end
        end
    end

    if !noeigs
        _plot_eigs()
    end

    # pick out up to four representative vpts from the list
    l = unique(Int.(round.((nvpts - 1) .* [1, 3, 5, 7] / 8 .+ 1)))
    ll = length(l)

    function _plot_impulse()
        # if there are too many inputs and outputs, skip
        if format == :html
            open(joinpath(dir_date, "$filename.html"), "a") do output_f
                println(output_f, "<h2>Impulse/Step response plots</h2>")
            end
        end

        if ll == 1
            for i in 1:nin
                # fill in for each selected vpt
                r = findall(impulse[:, i] .== 1)
                if length(r) > 0
                    t = results[l[1]].impulse_resp.time
                    imp = results[l[1]].impulse_resp.response[r, i]
                    label = input_names[i] * " 🡲 " .* hcat(output_names[r]...)
                    p = plot(
                        t,
                        imp;
                        lw=2,
                        label,
                        xlabel="Time [s]",
                        ylabel="Output",
                    )
                    if format == :html
                        open(joinpath(dir_date, "$filename.html"), "a") do output_f
                            show(output_f, MIME("text/html"), p)
                        end
                    else
                        display(p)
                    end

                    t = results[l[1]].step_resp.time
                    stp = results[l[1]].step_resp.response[r, i]
                    p = plot(
                        t,
                        stp;
                        label,
                        xlabel="Time [s]",
                        ylabel="Output",
                    )
                    if format == :html
                        open(joinpath(dir_date, "$filename.html"), "a") do output_f
                            show(output_f, MIME("text/html"), p)
                        end
                    else
                        display(p)
                    end
                end
            end
        else
            # loop over outputs and inputs and selected vpts
            for i in 1:nout
                for j in 1:nin
                    if impulse[i, j] == 1
                        # make empty plot
                        ylabel = input_names[j] * " 🡲 " * output_names[i]
                        p = plot(;
                            xlabel="Time [s]",
                            ylabel,
                        )
                        # fill in for each selected vpt
                        for k in l
                            t = results[k].impulse_resp.time
                            imp = results[k].impulse_resp.response[i, j]
                            lb = vpt_name[1] * "=$(my_round(vpts[k]))  $(vpt_name[3])"
                            p = plot!(p, t, imp; lw=2, label=lb)
                        end
                        if format == :html
                            open(joinpath(dir_date, "$filename.html"), "a") do output_f
                                show(output_f, MIME("text/html"), p)
                            end
                        else
                            display(p)
                        end

                        p = plot(;
                            xlabel="Time [s]",
                            ylabel,
                        )
                        # fill in for each selected vpt
                        for k in l
                            t = results[k].step_resp.time
                            stp = results[k].step_resp.response[i, j]
                            lb = vpt_name[1] * "=$(my_round(vpts[k]))  $(vpt_name[3])"
                            p = plot!(p, t, stp; lw=2, label=lb)
                        end
                        if format == :html
                            open(joinpath(dir_date, "$filename.html"), "a") do output_f
                                show(output_f, MIME("text/html"), p)
                            end
                        else
                            display(p)
                        end
                    end
                end
            end
        end
    end

    if nin * nout > 0 && any(impulse .== 1) && sum(impulse .== 1) < 32
        _plot_impulse()
    end

    function _plot_bode()

        if format == :html
            open(joinpath(dir_date, "$filename.html"), "a") do output_f
                println(output_f, "<h2>Bode plots</h2>")
            end
        end

        if ll == 1
            for i in 1:nin
                # fill in for each selected vpt
                r = findall(bode[:, i] .== 1)
                if length(r) > 0
                    w = results[l[1]].w / 2π
                    mag = [temp[j, i] for j in r, temp in results[l[1]].mag]
                    mag[findall(mag .> 100)] .= Inf
                    phs = [temp[j, i] for j in r, temp in results[l[1]].phase]
                    phs[phs.>1] .-= 360
                    phs[findall(abs.(diff(phs, dims=2)) .> 181)] .= Inf
                    label = hcat(output_names[r]...)
                    label .*= "/" * input_names[i]
                    xscale = :log10
                    xticks = w[isinteger.(log10.(w))]
                    p1 = plot(
                        w,
                        mag';
                        label,
                        xlabel="",
                        ylabel="Gain [dB]",
                        xscale,
                        xticks,
                        ylims=(-40, Inf),
                        widen=true,
                        bottom_margin=5mm,
                    )
                    p2 = plot(
                        w,
                        phs';
                        label="",
                        xlabel="Frequency [Hz]",
                        ylabel="Phase [°]",
                        xscale,
                        xticks,
                        ylims=(-360, 0),
                        widen=true,
                        yticks=-360:60:0,
                    )
                    # merge two subplots
                    p = plot(
                        p1,
                        p2,
                        layout=grid(2, 1, heights=[0.67, 0.33]),
                        size=(800, 600)
                    )
                    if format == :html
                        open(joinpath(dir_date, "$filename.html"), "a") do output_f
                            show(output_f, MIME("text/html"), p)
                        end
                    else
                        display(p)
                    end
                end
            end
        else
            # loop over outputs and inputs and selected vpts
            for i in 1:nout
                for j in 1:nin
                    if bode[i, j] == 1
                        # make empty plots of magnitude and phase
                        xscale = :log10
                        w = results[l[1]].w / 2π
                        xticks = w[isinteger.(log10.(w))]
                        ylabel = "|$(output_names[i])|/|$(input_names[j])| [dB]"
                        p1 = plot(;
                            xlabel="",
                            ylabel,
                            xscale,
                            xticks,
                            ylims=(-40, Inf),
                            widen=true,
                            bottom_margin=5mm,
                        )
                        ylabel = "∠ $(output_names[i])/$(input_names[j]) [°]"
                        p2 = plot(;
                            xlabel="Frequency [Hz]",
                            ylabel,
                            xscale,
                            xticks,
                            ylims=(-360, 0),
                            widen=true,
                            yticks=-360:60:0,
                        )
                        # fill in for each selected vpt
                        for k in l
                            w = results[k].w / 2π
                            mag = [temp[i, j] for temp in results[k].mag]
                            mag[findall(mag .> 100)] .= Inf
                            phs = [temp[i, j] for temp in results[k].phase]
                            phs[phs.>1] .-= 360
                            # set wrap arounds in phase to Inf to avoid jumps in plot
                            phs[findall(abs.(diff(phs)) .> 181)] .= Inf
                            lb = vpt_name[1] * "=$(my_round(vpts[k]))  $(vpt_name[3])"
                            p1 = plot!(p1, w, mag; lw=2, label=lb)
                            p2 = plot!(p2, w, phs; lw=2, label="")
                        end
                        # merge two subplots
                        p = plot(
                            p1,
                            p2,
                            layout=grid(2, 1, heights=[0.67, 0.33]),
                            size=(800, 600)
                        )
                        if format == :html
                            open(joinpath(dir_date, "$filename.html"), "a") do output_f
                                show(output_f, MIME("text/html"), p)
                            end
                        else
                            display(p)
                        end
                    end
                end
            end
        end
    end

    # if there are too many inputs and outputs, skip
    if nin * nout > 0 && any(bode .== 1) && sum(bode .== 1) < 32
        _plot_bode()
    end

    if length(plots) > 0
        if format == :html
            open(joinpath(dir_date, "$filename.html"), "a") do output_f
                println(output_f, "<h2>Time history and other plots</h2>")
                for p in plots
                    show(output_f, MIME("text/html"), p)
                end
            end
        else
            display.(plots)
        end
    end

    if format == :html
        open(joinpath(dir_date, "$filename.html"), "a") do output_f
            println(output_f, str_close)
        end
    end
end

#   xticks = 10.0 .^ collect(Int(round(log10(w[1]))):1:Int(round(log10(w[end]))))



#=
    # add the static preloads
    column_labels = ["Connector", "X", "Y", "Z", "L", "M", "N"]
    items = [
        systems[1].rigid_points
        systems[1].flex_points
        systems[1].springs
        systems[1].links
    ]
    temp =
        [getfield.(items, :name) my_round.(vcat(getfield.(items, :force)'...); lim=1e-4) my_round.(
            vcat(getfield.(items, :moment)'...);
            lim=1e-4,
        )]

    #=    for item in the_system.beams
           println(preload_f, "{$idx} {" * item.name * "} shear $(item.force[1][1]), $(item.force[1][2]), $(item.force[1][3]), $(norm(force[1]))")
           println(preload_f, "{} {} moment $(item.moment[1][1]), $(item.moment[1][2]), $(item.moment[1][3]), $(norm(item.moment[1]))")
           println(preload_f, "{} {} shear $(item.force[2][1]), $(item.force[2][2]), $(item.force[2][3]), $(norm(item.force[2]))")
           println(preload_f, "{} {} moment $(item.moment[2][1]), $(item.moment[2][2]), $(item.moment[2][3]), $(norm(item.moment[2]))")
           idx += 1
       end =#

    if format == :html
        println(output_f, "<h2>Preloads of first system</h2>")
        str = pretty_table(String, temp; column_labels, backend=:html)
        println(output_f, str)
        println(output_f, str_close)
        close(output_f)

    else
        println("Preloads of first system:")
        pretty_table(temp; column_labels, table_format=TextTableFormat(; @text__no_vertical_lines), fit_table_in_display_vertically=false)
    end
=#




