function summarize(
    system::mbd_system,
    results::EoM.analysis;
    plots = [],
    ss = ones(Int64, length(system.sensors), length(system.actuators)),
    bode = :default,
    impulse = ones(Int64, length(system.sensors), length(system.actuators)),
    format::Symbol = :screen,
    folder::String = "output",
    filename::String = system.name,
)
    summarize([system], 0, [results]; plots, ss, bode, impulse, format, folder, filename)
end

    # Copyright (C) 2020, Bruce Minaker

function summarize(
    systems::Vector{mbd_system},
    vpts,
    results::Vector{EoM.analysis};
    plots = [],
    ss = ones(Int64, length(systems[1].sensors), length(systems[1].actuators)),
    bode = :default,
    impulse = ones(Int64, length(systems[1].sensors), length(systems[1].actuators)),
    vpt_name = ["u" "Speed" "m/s"],
    format::Symbol = :screen,
    folder::String = "output",
    filename::String = systems[1].name,
    )

    println("Printing summary of the analysis of: $(systems[1].name)...")
    noeigs = false
    plotly()

    title = "EoM " * Dates.format(now(), "yyyy-mm-dd")
    titlefontsize = 7
    titlelocation = :left

#    extra_kwargs = Dict(:subplot => (; ))#width = 20))

    if format == :html

        # set up the paths
        dirs = setup(folder = folder, data = filename)
        dir_date = dirs[1]
        dir_time = dirs[2]
        dir_data = joinpath(dir_date, dir_time)

        # default html start and end text
        str_open = "<!doctype html><html lang=\"en\" ><head>\n    <title>EoM Analysis results</title>\n    <meta charset=\"utf-8\">\n    <meta name=\"description\" content=\"EoM Analysis result\">\n    <meta name=\"author\" content=\"automatically generated by EoM\">\n    <style>\n    table {\n    border-collapse: collapse;\n    }\n    td, th {\n    border: 1px solid #dddddd;\n    text-align: center;\n    padding: 8px;\n    }\n    tr:nth-child(even) {\n    background-color: #dddddd;\n    }\n    </style>\n</head>\n<body>\n"

        str_close = "</body>\n</html>"

        # open the base html file to write, and start filling it
        output_f = open(joinpath(dir_date, filename * ".html"), "w")
        println(output_f, str_open)
        println(output_f, "<img src=\"figures/eom_logo.png\" alt=\"Icon\" style=\"width:200px;\">")
        println(output_f, "<h1>Analysis results</h1>")
        println(output_f, "<p>Here are the results of the analysis of: $(systems[1].name)</p>")
    end

    # get names of inputs and outputs
    input_names = getfield.(systems[1].actuators, :name)
    input_units = uparse.(getfield.(systems[1].actuators, :units))
    output_names = getfield.(systems[1].sensors, :name)
    output_units = uparse.(getfield.(systems[1].sensors, :units))

    # get number of ins, outs, and number of vpts (velocity points)
    nin = length(input_names)
    nout = length(output_names)
    nvpts = length(vpts)

    # if there are too many inputs and outputs, skip
    if nin * nout > 0 && any(ss .== 1) && sum(ss .== 1) < 16
        labels = []
        gain = []
        # loop over outputs and inputs and vpts
        for i in 1:nout
            for j in 1:nin
                # n = (i - 1) * nin + j
                #if findnext(ss .== n, 1) !== nothing
                if ss[i, j] == 1
                    x = zeros(nvpts)
                    for k in 1:nvpts
                        x[k] = my_round(results[k].ss_resp[i, j])
                    end
                    push!(gain, x[1])
                    lb = "$(output_names[i])/$(input_names[j]) [$(output_units[i]/input_units[j])]"
                    push!(labels, lb)
                    # if many vpts, make plot vs velocity
                    if nvpts > 1
                        p = plot(
                            vpts,
                            x;
                            lw = 2,
                            xlabel = vpt_name[2] * " [$(vpt_name[3])]",
                            ylabel = lb,
                            label = "",
                            size = (800, 400),
                            title,
                            titlefontsize,
                            titlelocation,
                            extra_kwargs
                        )
                        if format == :html
                            path = joinpath(dir_data, "sstf_$(i)_$(j).html")
                            savefig(p, path)
                            f = open(path, "r")
                            println(output_f, read(f, String))
                            close(f)
                        else
                            display(p)
                        end
                    end
                end
            end
        end

        # if only one vpt, make table of the gains
        if nvpts == 1
            header = ["Output/Input", "Gain"]
            if format == :html
                println(output_f, "<h2>Steady state gains</h2>")
                str = pretty_table(String, [labels my_round.(gain)]; header, backend = Val(:html), standalone = false)
                println(output_f, str)
    
                path = joinpath(dir_data, "sstf.html")
                temp = open(path, "w")
                println(temp, str_open, str, str_close)
                close(temp)
            else
                println("Steady state gains:")
                pretty_table([labels my_round.(gain)]; header, vlines = :none)
            end
        end
    end

    if !noeigs
        # get eigenvalues
        l = length.(getfield.(results, :e_val))
        m = maximum(l)
        s = zeros(m, nvpts) * 1im
        for i in 1:nvpts
            s[1:l[i], i] = results[i].e_val
        end

        lz = length.(getfield.(results, :t_zero))
        mz = maximum(lz)
        sz = zeros(mz, nvpts) * 1im
        for i in 1:nvpts
            sz[1:lz[i], i] = results[i].t_zero
        end

        # for one velocity, chart of calcs from eigenvalues, otherwise plot eigenvalues
        if nvpts == 1
            omega = results[1].omega_n
            zeta = results[1].zeta
            tau = results[1].tau
            lambda = results[1].lambda
            header = ["No.", "σ±ωi [rad/s]", "ω_n [Hz]", "ζ", "τ [s]", "λ [s]"]

            if format == :html
                println(output_f, "<h2>Eigenvalues of minimal system</h2>")
                str = pretty_table(String,[1:1:l[1] my_round.([s omega zeta tau lambda])]; header, backend = Val(:html), standalone = false)
                println(output_f, str)

                path = joinpath(dir_data, "eigen.html")
                temp = open(path, "w")
                println(temp, str_open, str, str_close)
                close(temp)
            else
                println("Eigenvalues of minimal system:")
                pretty_table([1:1:l[1] my_round.([s omega zeta tau lambda])]; header, vlines = :none)
            end

            t_zero = results[1].t_zero
            t_zero_f = results[1].t_zero_f

            header = ["No.", "σ±ωi [rad/s]", "ω [Hz]"]
            if format == :html
                println(output_f, "<h2>Zeros of minimal system</h2>")
                str = pretty_table(String,[1:1:lz[1] my_round.([t_zero t_zero_f])]; header, backend = Val(:html), standalone = false)
                println(output_f, str)

                path = joinpath(dir_data, "zeros.html")
                temp = open(path, "w")
                println(temp, str_open, str, str_close)
                close(temp)
            else
                println("Zeros of minimal system:")
                pretty_table([1:1:lz[1] my_round.([t_zero t_zero_f])]; header, vlines = :none)
            end
        else

            # plot real and imaginary seperately
            sr = real.(s)
            si = imag.(s)

            # eliminate all zero rows
            tr = []
            for i in eachrow(sr)
                if any(i .!= 0)
                    push!(tr, i)
                end
            end
            sr = hcat(tr...)'
            tr = []
            for i in eachrow(si)
                if any(i .!= 0)
                    push!(tr, i)
                end
            end
            si = hcat(tr...)'

            # don't plot zeros - but can't have entire row of NaN
            sr[sr .== 0] .= NaN
            si[si .== 0] .= NaN

            seriestype = :scatter
            ms = 3
            p = plot(;
                xlabel = vpt_name[2] * " [$(vpt_name[3])]",
                ylabel = "Eigenvalue [rad/s]",
                size = (800, 400),
                title,
                titlefontsize,
                titlelocation,
                extra_kwargs
            )

            vsr = vec(sr')
            mc = RGB(0 / 255, 154 / 255, 250 / 255)
            label = "Real"
            u = size(sr, 1)
            vv = vcat(fill(vpts, u)...)
            if length(vsr) > 0
                plot!(p, vv, vsr; seriestype, mc, ms, label)
            end
            vsi = vec(si')
            mc = RGB(227 / 255, 111 / 255, 71 / 255)
            label = "Imaginary"
            u = size(si, 1)
            vv = vcat(fill(vpts, u)...)
            if length(vsi) > 0
                plot!(p, vv, vsi; seriestype, mc, ms, label)
            end

            if format == :html
                println(output_f, "<h2>Eigenvalue plots</h2>")
                path = joinpath(dir_data, "eigen.html")
                savefig(p, path)
                f = open(path, "r")
                println(output_f, read(f, String))
                close(f)
            else
                display(p)
            end

            label = ""
            mc = RGB(0 / 255, 154 / 255, 250 / 255)

            sr = real.(s)
            si = imag.(s)
            vsr = vec(sr')
            vsi = vec(si')

            p = plot(vsr, vsi;
                seriestype,
                aspect_ratio = :equal,
                mc,
                ms,
                label,
                xlabel = "Real part [rad/s]",
                ylabel = "Imaginary part [rad/s]",
                size = (800, 400),
                title,
                titlefontsize,
                titlelocation,
                extra_kwargs
            )

            if format == :html
                println(output_f, "<h2>Locus plots</h2>")
                path = joinpath(dir_data, "locus.html")
                savefig(p, path)
                f = open(path, "r")
                println(output_f, read(f, String))
                close(f)
            else
                display(p)
            end

            omega = treat(getfield.(results, :omega_n))
            mc = RGB(0 / 255, 154 / 255, 250 / 255)
            if length(omega) > 0
                po = plot(
                    vpts,
                    omega;
                    seriestype,
                    mc,
                    ms,
                    label,
                    xlabel = vpt_name[2] * " [$(vpt_name[3])]",
                    ylabel = "Natural frequency [Hz]",
                    ylims = (0, Inf),
                    size = (800, 400),
                    title,
                    titlefontsize,
                    titlelocation,
                    extra_kwargs
                )
                if format == :html
                    path = joinpath(dir_data, "omega.html")
                    savefig(po, path)
                    f = open(path, "r")
                    println(output_f, read(f, String))
                    close(f)
                else
                    display(po)
                end
            end

            zeta = treat(getfield.(results, :zeta))
            mc = RGB(0 / 255, 154 / 255, 250 / 255)
            if length(zeta) > 0
                pz = plot(
                    vpts,
                    zeta;
                    seriestype,
                    mc,
                    ms,
                    label,
                    xlabel = vpt_name[2] * " [$(vpt_name[3])]",
                    ylabel = "Damping ratio",
                    size = (800, 400),
                    title,
                    titlefontsize,
                    titlelocation,
                    extra_kwargs
                )
                if format == :html
                    path = joinpath(dir_data, "zeta.html")
                    savefig(pz, path)
                    f = open(path, "r")
                    println(output_f, read(f, String))
                    close(f)
                else
                    display(pz)
                end
            end

            tau = treat(getfield.(results, :tau))
            mc = RGB(0 / 255, 154 / 255, 250 / 255)
            if length(tau) > 0
                pt = plot(
                    vpts,
                    tau;
                    seriestype,
                    mc,
                    ms,
                    label,
                    xlabel = vpt_name[2] * " [$(vpt_name[3])]",
                    ylabel = "Time constant [s]",
                    size = (800, 400),
                    title,
                    titlefontsize,
                    titlelocation,
                    extra_kwargs
                )
                if format == :html
                    path = joinpath(dir_data, "tau.html")
                    savefig(pt, path)
                    f = open(path, "r")
                    println(output_f, read(f, String))
                    close(f)
                else
                    display(pt)
                end
            end

            lambda = treat(getfield.(results, :lambda))
            mc = RGB(0 / 255, 154 / 255, 250 / 255)
            if length(lambda) > 0
                pl = plot(
                    vpts,
                    lambda;
                    seriestype,
                    mc,
                    ms,
                    label,
                    xlabel = vpt_name[2] * " [$(vpt_name[3])]",
                    ylabel = "Wavelength [s]",
                    ylims = (0, Inf),
                    size = (800, 400),
                    title,
                    titlefontsize,
                    titlelocation,
                    extra_kwargs
                )
                if format == :html
                    path = joinpath(dir_data, "lambda.html")
                    savefig(pl, path)
                    f = open(path, "r")
                    println(output_f, read(f, String))
                    close(f)
                else
                    display(pl)
                end
            end
        end

        # print instant centre of body 1
        if nvpts == 1
            header = ["No.", "Eigenvalue", "x", "y", "z", "u_x", "u_y", "u_z"]
            temp = my_round.([results[1].mode_vals (results[1].centre[1:6, 1:end])'])
            if format == :html
                println(output_f, "<h2>Rotation centres of first body for all modes</h2>")
                link = []
                for i in axes(temp, 1)
                    push!(link, joinpath("<a href=\"$filename", "x3d", "mode_$(i)_s=$(round(results[1].mode_vals[i], digits=3)).html\">$i</a>"))
                end
                str = pretty_table(String, [link temp]; header, backend = Val(:html), allow_html_in_cells = true, standalone = false)
                println(output_f, str)
    
                path = joinpath(dir_data, "centres.html")
                temp = open(path, "w")
                println(temp, str_open, str, str_close)
                close(temp)
            else
                println("Rotation centres of first body for all modes:")
                pretty_table([1:1:size(temp, 1) temp]; header, vlines = :none)
            end
        end
    end

    if bode == :default
        isok(x) = (x == NoDims) 
        bode = isok.(dimension.(output_units * transpose(1 ./ input_units)))
    end

    if size(bode, 1) > nout || size(bode, 2) > nin
        error("Bode plot request dimensions are incompatible with system!")
    end

    # if there are too many inputs and outputs, skip
    if nin * nout > 0 && any(bode .== 1) && sum(bode .== 1) < 32
        
        if format == :html
            println(output_f, "<h2>Bode plots</h2>")
        end
        
        # pick out up to four representative vpts from the list
        l = unique(Int.(round.((nvpts - 1) .* [1, 3, 5, 7] / 8 .+ 1)))
        ll = length(l)

        if ll == 1
            for i in 1:nin
                # fill in for each selected vpt
                r = findall(bode[:, i] .== 1)
                if length(r) > 0
                    w = results[l[1]].w / 2π
                    mag = cat(results[l[1]].mag..., dims = 3)[r, i, :]
                    mag[findall(mag .> 100)] .= Inf
                    phs = cat(results[l[1]].phase..., dims = 3)[r, i, :]
                    phs[phs .> 0.1] .-= 360
                    phs[findall(abs.(diff(phs, dims = 2)) .> 250)] .= Inf
                    label = hcat(output_names[r]...)
                    label .*= "/" * input_names[i]
                    xscale = :log10
                    xticks = w[isinteger.(log10.(w))]
                    p1 = plot(
                        w,
                        mag';
                        lw = 2,
                        label,
                        xlabel = "",
                        ylabel = "Gain [dB]",
                        xscale,
                        xticks,
                        ylims = (-40, Inf),
                        title,
                        titlefontsize,
                        titlelocation,
                        bottom_margin = 5mm,
                        extra_kwargs
                    )
                    p2 = plot(
                        w,
                        phs';
                        lw = 2,
                        label = "",
                        xlabel = "Frequency [Hz]",
                        ylabel = "Phase [°]",
                        xscale,
                        xticks,
                        ylims = (-365, 5),
                        yticks = -360:60:0,
                        extra_kwargs
                    )
                    # merge two subplots
                    p = plot(
                        p1,
                        p2,
                        layout = grid(2, 1, heights = [0.66, 0.33]),
                        size = (800, 600)
                    )
                    if format == :html
                        path = joinpath(dir_data, "bode_$i.html")
                        savefig(p, path)
                        f = open(path, "r")
                        println(output_f, read(f, String))
                        close(f)
                    else
                        display(p)
                    end
                end
            end
        else
            # loop over outputs and inputs and selected vpts
            for i in 1:nout
                for j in 1:nin
                    if bode[i,j] == 1
                        # make empty plots of magnitude and phase
                        xscale = :log10
                        w = results[l[1]].w / 2π
                        xticks = w[isinteger.(log10.(w))]
                        ylabel = "|$(output_names[i])|/|$(input_names[j])| [dB]"
                        p1 = plot(;
                            xlabel = "",
                            ylabel,
                            xscale,
                            xticks,
                            ylims = (-40, Inf),
                            bottom_margin = 5mm,
                            title,
                            titlefontsize,
                            titlelocation,
                            extra_kwargs
                        )
                        ylabel = "∠ $(output_names[i])/$(input_names[j]) [°]"
                        p2 = plot(;
                            xlabel = "Frequency [Hz]",
                            ylabel,
                            xscale,
                            xticks,
                            ylims = (-365, 5),
                            yticks = -360:60:0,
                            extra_kwargs
                        )
                        # fill in for each selected vpt
                        for k in l
                            w = results[k].w / 2π
                            mag = cat(results[k].mag..., dims = 3)[i, j, :]
                            mag[findall(mag .> 100)] .= Inf
                            phs = cat(results[k].phase..., dims = 3)[i, j, :]
                            phs[phs .> 0] .-= 360
                            # set wrap arounds in phase to Inf to avoid jumps in plot
                            phs[findall(abs.(diff(phs)) .> 180)] .= Inf
                            lb = vpt_name[1] * "=$(my_round(vpts[k]))  $(vpt_name[3])"
                            p1 = plot!(p1, w, mag; lw = 2, label = lb)
                            p2 = plot!(p2, w, phs; lw = 2, label = "")
                        end
                        # merge two subplots
                        p = plot(
                            p1,
                            p2,
                            layout = grid(2, 1, heights = [0.66, 0.33]),
                            size = (800, 600)
                        )
                        if format == :html
                            path = joinpath(dir_data, "bode_$(i)_$(j).html")
                            savefig(p, path)
                            f = open(path, "r")
                            println(output_f, read(f, String))
                            close(f)
                        else
                            display(p)
                        end
                    end
                end
            end
        end

        if format == :html
            println(output_f, "<h2>Impulse response plots</h2>")
        end

        if ll == 1
            for i in 1:nin
                # fill in for each selected vpt
                r = findall(impulse[:, i] .== 1)
                if length(r) > 0
                    t = results[l[1]].impulse_t
                    imp = cat(results[l[1]].impulse..., dims = 3)[r, i, :]
                    label = hcat(output_names[r]...)
                    label .*= "/" * input_names[i]
                    p = plot(
                        t,
                        imp';
                        lw = 2,
                        label,
                        xlabel = "Time [s]",
                        ylabel = "Output",
                        size = (800, 400),
                        title,
                        titlefontsize,
                        titlelocation,
                        extra_kwargs
                    )
                    if format == :html
                        path = joinpath(dir_data, "impulse_$i.html")
                        savefig(p, path)
                        f = open(path, "r")
                        println(output_f, read(f, String))
                        close(f)
                    else
                        display(p)
                    end
                end
            end
        else
            # loop over outputs and inputs and selected vpts
            for i in 1:nout
                for j in 1:nin
                    if impulse[i,j] == 1
                        # make empty plot
                        ylabel = "|$(output_names[i])|/|$(input_names[j])| "
                        p = plot(;
                            xlabel = "Time [s]",
                            ylabel,
                            size = (800, 400),
                            title,
                            titlefontsize,
                            titlelocation,
                            extra_kwargs
                        )
                        # fill in for each selected vpt
                        for k in l
                            t = results[k].impulse_t
                            imp = cat(results[k].impulse..., dims = 3)[i, j, :]
                            lb = vpt_name[1] * "=$(my_round(vpts[k]))  $(vpt_name[3])"
                            p = plot!(p, t, imp; lw = 2, label = lb)
                        end
                        if format == :html
                            path = joinpath(dir_data, "impulse_$(i)_$(j).html")
                            savefig(p, path)
                            f = open(path, "r")
                            println(output_f, read(f, String))
                            close(f)
                        else
                            display(p)
                        end
                    end
                end
            end
        end
    end


    if length(plots) > 0
        if format == :html
            println(output_f, "<h2>Time history and other plots</h2>")
            for i in eachindex(plots)
                path = joinpath(dir_data, "plot_$i.html")
                savefig(plots[i], path)
                f = open(path, "r")
                println(output_f, read(f, String))
                close(f)
            end
        else
            display.(plots)
        end
    end

    # add the static preloads
    header = ["Connector", "X", "Y", "Z", "L", "M", "N"]
    items = [
        systems[1].rigid_points
        systems[1].flex_points
        systems[1].springs
        systems[1].links
    ]
    temp =
        [getfield.(items, :name) my_round.(vcat(getfield.(items, :force)'...); lim = 1e-4) my_round.(
            vcat(getfield.(items, :moment)'...);
            lim = 1e-4,
        )]

    #=    for item in the_system.beams
           println(preload_f, "{$idx} {" * item.name * "} shear $(item.force[1][1]), $(item.force[1][2]), $(item.force[1][3]), $(norm(force[1]))")
           println(preload_f, "{} {} moment $(item.moment[1][1]), $(item.moment[1][2]), $(item.moment[1][3]), $(norm(item.moment[1]))")
           println(preload_f, "{} {} shear $(item.force[2][1]), $(item.force[2][2]), $(item.force[2][3]), $(norm(item.force[2]))")
           println(preload_f, "{} {} moment $(item.moment[2][1]), $(item.moment[2][2]), $(item.moment[2][3]), $(norm(item.moment[2]))")
           idx += 1
       end =#

    if format == :html
        println(output_f, "<h2>Preloads of first system</h2>")
        str = pretty_table(String, temp; header, backend = Val(:html), standalone = false)
        println(output_f, str)

        path = joinpath(dir_data, "preloads.html")
        temp = open(path, "w")
        println(temp, str_open, str, str_close)
        close(temp)
        # print the end and close the output
        println(output_f, str_close)
        close(output_f)

    else
        println("Preloads of first system:")
        pretty_table(temp; header, vlines = :none)
    end
end

            # for i in axes(si, 1)
            #     if any(si[i, :] .!= 0)
            #         push!(tr, i)
            #     end
            # end
            # si = si[tr, :]

#   xticks = 10.0 .^ collect(Int(round(log10(w[1]))):1:Int(round(log10(w[end]))))

#=                     if output_units[i] == input_units[j]
                        str_u = ""
                    elseif contains(output_units[i], input_units[j])
                        if contains(output_units[i], "/")
                            str_u = " [$(replace(output_units[i], input_units[j] => "1"))]"
                        else
                            str_u = " [$(replace(output_units[i], input_units[j] => ""))]"
                        end
                    else
                        str_u = " [$(output_units[i])/$(input_units[j])]"
                    end =#
