function summarize(
    system::mbd_system,
    results::EoM.analysis;
    plots=[],
    ss::Union{Symbol,Matrix,Vector}=:default,
    bode::Union{Symbol,Matrix,Vector}=:default,
    impulse::Union{Symbol,Matrix,Vector}=:default,
    format::Symbol=:screen,
    folder::String="output",
    filename::String=system.name,
)
    summarize([system], 0, [results]; plots, ss, bode, impulse, format, folder, filename)
end

# Copyright (C) 2020, Bruce Minaker

function summarize(
    systems::Vector{mbd_system},
    vpts,
    results::Vector{EoM.analysis};
    plots=[],
    ss::Union{Symbol,Matrix,Vector}=:default,
    bode::Union{Symbol,Matrix,Vector}=:default,
    impulse::Union{Symbol,Matrix,Vector}=:default,
    vpt_name=["u" "Speed" "m/s"],
    format::Symbol=:screen,
    folder::String="output",
    filename::String=systems[1].name,
)

    println("Printing summary of the analysis of: $(systems[1].name)...")

    # get names of inputs and outputs
    input_names = getfield.(systems[1].actuators, :name)
    input_units = uparse.(getfield.(systems[1].actuators, :units))
    output_names = getfield.(systems[1].sensors, :name)
    output_units = uparse.(getfield.(systems[1].sensors, :units))

    # get number of ins, outs, and number of vpts (velocity points)
    nin = length(input_names)
    nout = length(output_names)
    nvpts = length(vpts)

    noeigs = false

    if ss == :default
        ss = results[1].ss
    end

    if ss == :default
        ss = ones(nout, nin)
    elseif typeof(ss) == Symbol
        ss = zeros(nout, nin)
    end

    if size(ss, 1) != nout || size(ss, 2) != nin
        error("Steady state plot request dimensions are incompatible with system!")
    end

    if bode == :default
        bode = results[1].bode
    end

    if bode == :default
        isok(x) = (x == NoDims)
        bode = isok.(dimension.(output_units * transpose(1 ./ input_units)))
    elseif typeof(bode) == Symbol
        bode = zeros(nout, nin)
    end

    if size(bode, 1) != nout || size(bode, 2) != nin
        error("Bode plot request dimensions are incompatible with system!")
    end

    if impulse == :default
        impulse = results[1].impulse
    end

    if impulse == :default
        impulse = ones(nout, nin)
    elseif typeof(impulse) == Symbol
        impulse = zeros(nout, nin)
    end

    if size(impulse, 1) != nout || size(impulse, 2) != nin
        error("Impulse response plot request dimensions are incompatible with system!")
    end

    step_r = impulse
 
    if !isdefined(Main, :VSCodeServer)
        println("No VSCode detected, enforcing html format output...")
        format = :html
    end

    title = "EoM " * Dates.format(now(), "yyyy-mm-dd")
    titlefontsize = 7
    titlelocation = :left

    if format == :html

        # set up the paths
        dir_date = setup(; folder)

        # default html start and end text
        str_open = "<!doctype html><html lang=\"en\" ><head>\n    <title>EoM Analysis results</title>\n    <meta charset=\"utf-8\">\n    <meta name=\"description\" content=\"EoM Analysis result\">\n    <meta name=\"author\" content=\"automatically generated by EoM\">\n    <style>\n    table {\n    border-collapse: collapse;\n    }\n    td, th {\n    border: 1px solid #dddddd;\n    text-align: center;\n    padding: 8px;\n    }\n    tr:nth-child(even) {\n    background-color: #dddddd;\n    }\n    </style>\n</head>\n<body>\n"

        str_close = "</body>\n</html>"

        # open the base html file to write, and start filling it
        output_f = open(joinpath(dir_date, "$filename.html"), "w")
        println(output_f, str_open)
        println(output_f, "<img src=\"eom_logo.png\" alt=\"Icon\" style=\"width:200px;\">")
        println(output_f, "<h1>Analysis results</h1>")
        println(output_f, "<p>Here are the results of the analysis of: $(systems[1].name)</p>")
    end

    # if there are too many inputs and outputs, skip
    if nin * nout > 0 && any(ss .== 1) && sum(ss .== 1) < 16
        labels = []
        gain = []
        # loop over outputs and inputs and vpts
        for i in 1:nout
            for j in 1:nin
                # n = (i - 1) * nin + j
                #if findnext(ss .== n, 1) !== nothing
                if ss[i, j] == 1
                    x = zeros(nvpts)
                    for k in 1:nvpts
                        x[k] = my_round(results[k].ss_resp[i, j])
                    end
                    push!(gain, x[1])
                    lb = "$(output_names[i])/$(input_names[j]) [$(output_units[i]/input_units[j])]"
                    push!(labels, lb)
                    # if many vpts, make plot vs velocity
                    if nvpts > 1
                        p = plot(
                            vpts,
                            x;
                            lw=2,
                            xlabel=vpt_name[2] * " [$(vpt_name[3])]",
                            ylabel=lb,
                            label="",
                            size=(800, 400),
                            title,
                            titlefontsize,
                            titlelocation,
                            #extra_kwargs
                        )
                        if format == :html
                            show(output_f, MIME("text/html"), p)
                        else
                            display(p)
                        end
                    end
                end
            end
        end

        # if only one vpt, make table of the gains
        if nvpts == 1
            column_labels = ["Output/Input", "Gain"]
            if format == :html
                println(output_f, "<h2>Steady state gains</h2>")
                str = pretty_table(String, [labels my_round.(gain)]; column_labels, backend=:html)
                println(output_f, str)
            else
                println("Steady state gains:")
                pretty_table([labels my_round.(gain)]; column_labels, table_format = TextTableFormat(; @text__no_vertical_lines), fit_table_in_display_vertically=false)
            end
        end
    end

    if !noeigs
        # get eigenvalues
        l = length.(getfield.(results, :e_val))
        m = maximum(l)
        s = zeros(m, nvpts) * 1im
        for i in 1:nvpts
            s[1:l[i], i] = results[i].e_val
        end

        zs = getfield.(results, :t_zero)
        zsv = [vcat(zs[i][:]...) for i in 1:nvpts]
        lz = length.(zsv)
        mz = maximum(lz)
        sz = zeros(mz, nvpts) * 1im
        for i in 1:nvpts
            sz[1:lz[i], i] = zsv[i]
        end

        # for one velocity, chart of calcs from eigenvalues, otherwise plot eigenvalues
        if nvpts == 1
            omega = results[1].omega_n
            zeta = results[1].zeta
            tau = results[1].tau
            lambda = results[1].lambda
            column_labels = ["No.", "σ±ωi [rad/s]", "ω_n [Hz]", "ζ", "τ [s]", "λ [s]"]

            if format == :html
                println(output_f, "<h2>Eigenvalues of minimal system</h2>")
                str = pretty_table(String, [1:1:l[1] my_round.([s omega zeta tau lambda])]; column_labels, backend=:html)
                println(output_f, str)
            else
                println("Eigenvalues of minimal system:")
                pretty_table([1:1:l[1] my_round.([s omega zeta tau lambda])]; column_labels, table_format = TextTableFormat(; @text__no_vertical_lines), fit_table_in_display_vertically=false)
            end

            t_zero = vcat(results[1].t_zero[:]...)
            t_zero_f = vcat(results[1].t_zero_f[:]...)
            if length(t_zero) < 200
                column_labels = ["No.", "σ±ωi [rad/s]", "ω [Hz]"]
                if format == :html
                    println(output_f, "<h2>Zeros of minimal system</h2>")
                    str = pretty_table(String, [1:1:lz[1] my_round.([t_zero t_zero_f])]; column_labels, backend=:html)
                    println(output_f, str)
                else
                    println("Zeros of minimal system:")
                    pretty_table([1:1:lz[1] my_round.([t_zero t_zero_f])]; column_labels, table_format = TextTableFormat(; @text__no_vertical_lines), fit_table_in_display_vertically=false)
                end
            end
        else

            seriestype = :scatter
            label = reshape(["$(vpt_name[1])=$i" for i in vpts], 1, nvpts)
            mc = RGB(0 / 255, 154 / 255, 250 / 255)
            ms = 3

            sr = real.(s)
            si = imag.(s)
            vsr = vec(sr')
            vsi = vec(si')

            p = plot(vsr', vsi';
                seriestype,
                aspect_ratio=:equal,
                mc,
                ms,
                label,
                xlabel="Real part [rad/s]",
                ylabel="Imaginary part [rad/s]",
                size=(800, 400),
                title,
                legend=false,
                marker=:o,
                titlefontsize,
                titlelocation,
                #extra_kwargs
            )

            if format == :html
                println(output_f, "<h2>Locus plots</h2>")
                show(output_f, MIME("text/html"), p)
            else
                display(p)
            end

            # eliminate all zero rows
            nonzero_rows = findall(row -> any(row .!= 0), eachrow(sr))
            sr = sr[nonzero_rows, :]

            nonzero_rows = findall(row -> any(row .!= 0), eachrow(si))
            si = si[nonzero_rows, :]

            # don't plot zeros - but can't have entire row of NaN
            sr[sr.==0] .= NaN
            si[si.==0] .= NaN
            vsr = vec(sr')
            vsi = vec(si')
            if minimum(vsr) < -100
                yliml = -100
            else
                yliml = -Inf
            end

            p = plot(;
                xlabel=vpt_name[2] * " [$(vpt_name[3])]",
                ylabel="Eigenvalue [rad/s]",
                size=(800, 400),
                title,
                titlefontsize,
                titlelocation,
                ylims=(yliml, Inf),
                widen=true,
                #extra_kwargs
            )

            mc = RGB(0 / 255, 154 / 255, 250 / 255)
            label = "Real"
            u = size(sr, 1)
            vv = vcat(fill(vpts, u)...)
            if length(vsr) > 0
                plot!(p, vv, vsr; seriestype, mc, ms, label)
            end
            mc = RGB(227 / 255, 111 / 255, 71 / 255)
            label = "Imaginary"
            u = size(si, 1)
            vv = vcat(fill(vpts, u)...)
            if length(vsi) > 0
                plot!(p, vv, vsi; seriestype, mc, ms, label)
            end

            if format == :html
                println(output_f, "<h2>Eigenvalue plots</h2>")
                show(output_f, MIME("text/html"), p)
            else
                display(p)
            end

            mc = RGB(0 / 255, 154 / 255, 250 / 255)
            label = ""

            omega = treat(getfield.(results, :omega_n), 1000)
            if length(omega) > 0
                po = plot(
                    vpts,
                    omega;
                    seriestype,
                    mc,
                    ms,
                    label,
                    xlabel=vpt_name[2] * " [$(vpt_name[3])]",
                    ylabel="Natural frequency [Hz]",
                    ylims=(0, Inf),
                    widen=true,
                    size=(800, 400),
                    title,
                    titlefontsize,
                    titlelocation,
                    #extra_kwargs
                )
                if format == :html
                    show(output_f, MIME("text/html"), po)
                else
                    display(po)
                end
            end

            zeta = treat(getfield.(results, :zeta), 1)
            if length(zeta) > 0
                pz = plot(
                    vpts,
                    zeta;
                    seriestype,
                    mc,
                    ms,
                    label,
                    xlabel=vpt_name[2] * " [$(vpt_name[3])]",
                    ylabel="Damping ratio",
                    size=(800, 400),
                    title,
                    titlefontsize,
                    titlelocation,
                    #extra_kwargs
                )
                if format == :html
                    show(output_f, MIME("text/html"), pz)
                else
                    display(pz)
                end
            end

            tau = treat(getfield.(results, :tau), 100)
            if length(tau) > 0
                pt = plot(
                    vpts,
                    tau;
                    seriestype,
                    mc,
                    ms,
                    label,
                    xlabel=vpt_name[2] * " [$(vpt_name[3])]",
                    ylabel="Time constant [s]",
                    size=(800, 400),
                    title,
                    titlefontsize,
                    titlelocation,
                    #extra_kwargs
                )
                if format == :html
                    show(output_f, MIME("text/html"), pt)
                else
                    display(pt)
                end
            end

            lambda = treat(getfield.(results, :lambda), 100)
            if length(lambda) > 0
                pl = plot(
                    vpts,
                    lambda;
                    seriestype,
                    mc,
                    ms,
                    label,
                    xlabel=vpt_name[2] * " [$(vpt_name[3])]",
                    ylabel="Wavelength [s]",
                    ylims=(0, Inf),
                    size=(800, 400),
                    title,
                    titlefontsize,
                    titlelocation,
                    #extra_kwargs
                )
                if format == :html
                    show(output_f, MIME("text/html"), pl)
                else
                    display(pl)
                end
            end

            szr = real.(sz)
            szi = imag.(sz)

            # eliminate all zero rows
            nonzero_rows = findall(row -> any(row .!= 0), eachrow(szr))
            szr = szr[nonzero_rows, :]

            nonzero_rows = findall(row -> any(row .!= 0), eachrow(szi))
            szi = szi[nonzero_rows, :]

            # don't plot zeros - but can't have entire row of NaN
            szr[szr.==0] .= NaN
            szi[szi.==0] .= NaN
            vszr = vec(szr')
            vszi = vec(szi')
            display(vszr)
            display(length(vszr))
            if length(vszr) > 0 && minimum(filter(isfinite, vszr)) < -100
                yliml = -100
            else
                yliml = -Inf
            end

            p = plot(;
                xlabel=vpt_name[2] * " [$(vpt_name[3])]",
                ylabel="Zero [rad/s]",
                size=(800, 400),
                title,
                titlefontsize,
                titlelocation,
                ylims=(yliml, Inf),
                widen=true,
                #extra_kwargs
            )

            mc = RGB(0 / 255, 154 / 255, 250 / 255)
            label = "Real"
            u = size(szr, 1)
            vv = vcat(fill(vpts, u)...)
            if length(vszr) > 0
                plot!(p, vv, vszr; seriestype, mc, ms, label)
            end
            mc = RGB(227 / 255, 111 / 255, 71 / 255)
            label = "Imaginary"
            u = size(szi, 1)
            vv = vcat(fill(vpts, u)...)
            if length(vszi) > 0
                plot!(p, vv, vszi; seriestype, mc, ms, label)
            end

            if format == :html
                println(output_f, "<h2>Zeros plot</h2>")
                show(output_f, MIME("text/html"), p)
            else
                display(p)
            end
        end

        # print instant centre of body 1
        if nvpts == 1
            column_labels = ["No.", "Eigenvalue", "x", "y", "z", "u_x", "u_y", "u_z"]
            temp = my_round.([results[1].mode_vals (results[1].centre[1:6, 1:end])'])
            if format == :html
                println(output_f, "<h2>Rotation centres of first body for all modes, relative to G:</h2>")
                link = []
                for i in axes(temp, 1)
                    push!(link, joinpath("<a href=\"$filename", "x3d", "mode_$(i)_s=$(round(results[1].mode_vals[i], digits=3)).html\">$i</a>"))
                end
                str = pretty_table(String, [link temp]; column_labels, backend=:html, allow_html_in_cells=true)
                println(output_f, str)
            else
                println("Rotation centres of first body for all modes, relative to G:")
                pretty_table([1:1:size(temp, 1) temp]; column_labels, table_format = TextTableFormat(; @text__no_vertical_lines), fit_table_in_display_vertically=false)
            end
        end
    end

    # pick out up to four representative vpts from the list
    l = unique(Int.(round.((nvpts - 1) .* [1, 3, 5, 7] / 8 .+ 1)))
    ll = length(l)

    # if there are too many inputs and outputs, skip
    if nin * nout > 0 && any(impulse .== 1) && sum(impulse .== 1) < 32

        if format == :html
            println(output_f, "<h2>Impulse/Step response plots</h2>")
        end

        if ll == 1
            for i in 1:nin
                # fill in for each selected vpt
                r = findall(impulse[:, i] .== 1)
                if length(r) > 0
                    t = results[l[1]].impulse_resp.time
                    imp = results[l[1]].impulse_resp.response[r, i]
                    label = input_names[i] * " 🡲 " .* hcat(output_names[r]...)
                    p = plot(
                        t,
                        imp;
                        lw=2,
                        label,
                        xlabel="Time [s]",
                        ylabel="Output",
                        size=(800, 400),
                        title,
                        titlefontsize,
                        titlelocation,
                        #extra_kwargs
                    )
                    if format == :html
                        show(output_f, MIME("text/html"), p)
                    else
                        display(p)
                    end

                    t = results[l[1]].step_resp.time
                    stp = results[l[1]].step_resp.response[r, i]
                    p = plot(
                        t,
                        stp;
                        lw=2,
                        label,
                        xlabel="Time [s]",
                        ylabel="Output",
                        size=(800, 400),
                        title,
                        titlefontsize,
                        titlelocation,
                        #extra_kwargs
                    )
                    if format == :html
                        show(output_f, MIME("text/html"), p)
                    else
                        display(p)
                    end
                end
            end
        else
            # loop over outputs and inputs and selected vpts
            for i in 1:nout
                for j in 1:nin
                    if impulse[i, j] == 1
                        # make empty plot
                        ylabel = input_names[j] * " 🡲 " * output_names[i]
                        p = plot(;
                            xlabel="Time [s]",
                            ylabel,
                            size=(800, 400),
                            title,
                            titlefontsize,
                            titlelocation,
                            #extra_kwargs
                        )
                        # fill in for each selected vpt
                        for k in l
                            t = results[k].impulse_resp.time
                            imp = results[k].impulse_resp.response[i, j]
                            lb = vpt_name[1] * "=$(my_round(vpts[k]))  $(vpt_name[3])"
                            p = plot!(p, t, imp; lw=2, label=lb)
                        end
                        if format == :html
                            show(output_f, MIME("text/html"), p)
                        else
                            display(p)
                        end

                        p = plot(;
                            xlabel="Time [s]",
                            ylabel,
                            size=(800, 400),
                            title,
                            titlefontsize,
                            titlelocation,
                            #extra_kwargs
                        )
                        # fill in for each selected vpt
                        for k in l
                            t = results[k].step_resp.time
                            stp = results[k].step_resp.response[i, j]
                            lb = vpt_name[1] * "=$(my_round(vpts[k]))  $(vpt_name[3])"
                            p = plot!(p, t, stp; lw=2, label=lb)
                        end
                        if format == :html
                            show(output_f, MIME("text/html"), p)
                        else
                            display(p)
                        end
                    end
                end
            end
        end
    end

    # if there are too many inputs and outputs, skip
    if nin * nout > 0 && any(bode .== 1) && sum(bode .== 1) < 32

        if format == :html
            println(output_f, "<h2>Bode plots</h2>")
        end

        if ll == 1
            for i in 1:nin
                # fill in for each selected vpt
                r = findall(bode[:, i] .== 1)
                if length(r) > 0
                    w = results[l[1]].w / 2π
                    mag = [temp[j, i] for j in r, temp in results[l[1]].mag]
                    mag[findall(mag .> 100)] .= Inf
                    phs = [temp[j, i] for j in r, temp in results[l[1]].phase]
                    phs[phs.>1] .-= 360
                    phs[findall(abs.(diff(phs, dims=2)) .> 181)] .= Inf
                    label = hcat(output_names[r]...)
                    label .*= "/" * input_names[i]
                    xscale = :log10
                    xticks = w[isinteger.(log10.(w))]
                    p1 = plot(
                        w,
                        mag';
                        lw=2,
                        label,
                        xlabel="",
                        ylabel="Gain [dB]",
                        xscale,
                        xticks,
                        ylims=(-40, Inf),
                        widen=true,
                        title,
                        titlefontsize,
                        titlelocation,
                        bottom_margin=5mm,
                        #extra_kwargs
                    )
                    p2 = plot(
                        w,
                        phs';
                        lw=2,
                        label="",
                        xlabel="Frequency [Hz]",
                        ylabel="Phase [°]",
                        xscale,
                        xticks,
                        ylims=(-360, 0),
                        widen=true,
                        yticks=-360:60:0,
                        #extra_kwargs
                    )
                    # merge two subplots
                    p = plot(
                        p1,
                        p2,
                        layout=grid(2, 1, heights=[0.67, 0.33]),
                        size=(800, 600)
                    )
                    if format == :html
                        show(output_f, MIME("text/html"), p)
                    else
                        display(p)
                    end
                end
            end
        else
            # loop over outputs and inputs and selected vpts
            for i in 1:nout
                for j in 1:nin
                    if bode[i, j] == 1
                        # make empty plots of magnitude and phase
                        xscale = :log10
                        w = results[l[1]].w / 2π
                        xticks = w[isinteger.(log10.(w))]
                        ylabel = "|$(output_names[i])|/|$(input_names[j])| [dB]"
                        p1 = plot(;
                            xlabel="",
                            ylabel,
                            xscale,
                            xticks,
                            ylims=(-40, Inf),
                            widen=true,
                            bottom_margin=5mm,
                            title,
                            titlefontsize,
                            titlelocation,
                            #extra_kwargs
                        )
                        ylabel = "∠ $(output_names[i])/$(input_names[j]) [°]"
                        p2 = plot(;
                            xlabel="Frequency [Hz]",
                            ylabel,
                            xscale,
                            xticks,
                            ylims=(-360, 0),
                            widen=true,
                            yticks=-360:60:0,
                            #extra_kwargs
                        )
                        # fill in for each selected vpt
                        for k in l
                            w = results[k].w / 2π
                            mag = [temp[i, j] for temp in results[k].mag]
                            mag[findall(mag .> 100)] .= Inf
                            phs = [temp[i, j] for temp in results[k].phase]
                            phs[phs.>1] .-= 360
                            # set wrap arounds in phase to Inf to avoid jumps in plot
                            phs[findall(abs.(diff(phs)) .> 181)] .= Inf
                            lb = vpt_name[1] * "=$(my_round(vpts[k]))  $(vpt_name[3])"
                            p1 = plot!(p1, w, mag; lw=2, label=lb)
                            p2 = plot!(p2, w, phs; lw=2, label="")
                        end
                        # merge two subplots
                        p = plot(
                            p1,
                            p2,
                            layout=grid(2, 1, heights=[0.67, 0.33]),
                            size=(800, 600)
                        )
                        if format == :html
                            show(output_f, MIME("text/html"), p)
                        else
                            display(p)
                        end
                    end
                end
            end
        end
    end

    if length(plots) > 0
        plot!.(plots; title, titlefontsize, titlelocation)
        if format == :html
            println(output_f, "<h2>Time history and other plots</h2>")
            for p in plots
                show(output_f, MIME("text/html"), p)
            end
        else
            display.(plots)
        end
    end

    # add the static preloads
    column_labels = ["Connector", "X", "Y", "Z", "L", "M", "N"]
    items = [
        systems[1].rigid_points
        systems[1].flex_points
        systems[1].springs
        systems[1].links
    ]
    temp =
        [getfield.(items, :name) my_round.(vcat(getfield.(items, :force)'...); lim=1e-4) my_round.(
            vcat(getfield.(items, :moment)'...);
            lim=1e-4,
        )]

    #=    for item in the_system.beams
           println(preload_f, "{$idx} {" * item.name * "} shear $(item.force[1][1]), $(item.force[1][2]), $(item.force[1][3]), $(norm(force[1]))")
           println(preload_f, "{} {} moment $(item.moment[1][1]), $(item.moment[1][2]), $(item.moment[1][3]), $(norm(item.moment[1]))")
           println(preload_f, "{} {} shear $(item.force[2][1]), $(item.force[2][2]), $(item.force[2][3]), $(norm(item.force[2]))")
           println(preload_f, "{} {} moment $(item.moment[2][1]), $(item.moment[2][2]), $(item.moment[2][3]), $(norm(item.moment[2]))")
           idx += 1
       end =#

    if format == :html
        println(output_f, "<h2>Preloads of first system</h2>")
        str = pretty_table(String, temp; column_labels, backend=:html)
        println(output_f, str)
        println(output_f, str_close)
        close(output_f)

    else
        println("Preloads of first system:")
        pretty_table(temp; column_labels, table_format = TextTableFormat(; @text__no_vertical_lines), fit_table_in_display_vertically=false)
    end
end

#   xticks = 10.0 .^ collect(Int(round(log10(w[1]))):1:Int(round(log10(w[end]))))
